#!/bin/sh
WINEPREFIX="$(echo ${HOME})/.var/app/com.blizzard.Battle.net/data/wine" # Required to reset the WINEPREFIX here because wine does not like the relative path set in the manifest

echo "Checking if Battle.net is already installed"
if [ -d "${WINEPREFIX}/drive_c/Program Files (x86)/Battle.net/" ]; then
  echo "Battle.net is installed"

  echo "Setting up Discord rich presence"
  for i in {0..9}; do
      test -S $XDG_RUNTIME_DIR/discord-ipc-$i ||
      ln -sf {app/com.discordapp.Discord,$XDG_RUNTIME_DIR}/discord-ipc-$i;
  done

  echo "Changing directory to ${WINEPREFIX}/drive_c/Program Files (x86)/Battle.net/"
  cd "${WINEPREFIX}/drive_c/Program Files (x86)/Battle.net/"

  echo "Launching Battle.net and switching to Hearthstone"
  wine "${WINEPREFIX}/drive_c/Program Files (x86)/Battle.net/Battle.net.exe" --exec="launch WTCG"
else
  echo "Battle.net is not installed"

  echo "Launching Battle.net Flatpak"
  flatpak-spawn --host flatpak run com.blizzard.Battle.net
fi